Bot_name: "Bearish_bot"
Token: "YOUR_TOKEN_HERE"
Check_in_time: 60
Guild_id: 123456789
Webhook_url: "YOUR_WEBHOOK_HERE"
Age_requirement: 15
Ban_member: False
Dry_run: false
Whitelist_active: False
Whitelist:
- 329173372149825539
Send_sentence?: true
Channel_id: 123456789
Message_time: 10
Sentence_Kick/Ban: Be gone you idiot